### ISSUE TITLE
"qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "" error on 3rd release

### ISSUE THREAD

**Issue by macpod** [BatchDrake/SigDigger#1]
I tried testing out the pre-compiled binaries (specifically the 3rd release) on a Linux Mint 19 system (Ubuntu 18.04 lts base). If I run this I receive the following error:
"qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

I think qt5/plugins/platforms/libdxcb.so needs to be included?

I tried installing it via apt qt5dxcb-plugin but the current qt core version in the distro repos is not recent (5.9.5 per qmake). I also tried deleting the bundled qt core lib to see if it would use my installed qt core lib but there is a version check that stopped that effort quickly :)

I can't say if it is the best solution for this software but have you checked out AppImage for distributing binaries? CubicSDR uses this as a reference.
Alternatively maybe sdrangel's deb pkg approach could be referenced.

**Comment by BatchDrake** [comment]
Definitely, AppImage would be ideal but I didn't have time to read the docs. I tried .deb packages in the past, but preparing the environment was such a mess that I gave up. 

I think that instead of fixing this issue I'll invest some effort on learning how to use AppImage. Thanks for the tip!
