### ISSUE TITLE
Cannot create audio playback object: audio support disabled at compile time

### ISSUE THREAD

**Issue by robertofocke** [BatchDrake/SigDigger#100]
I installed SigDigger on kali linux. Cannot create audio playback object: audio support disabled at compile time.
![kali](https://user-images.githubusercontent.com/13512662/80309423-5a28c480-87ab-11ea-81d3-f61fc243af04.png)

**Comment by BatchDrake** [comment]
You need to install `libasound2-dev` with `apt` and then build SigDigger (and only SigDigger) from scratch, starting by a `make clean` on SigDigger's source directory.

**Comment by robertofocke** [comment]
![image](https://user-images.githubusercontent.com/13512662/80311858-80a12c80-87b8-11ea-8f88-ce38752848f4.png)

**Comment by BatchDrake** [comment]
Wow. This is odd. It seems like a soundcard issue. Can you play audio in your Kali at all? Could you show me your virtual soundcard config in VirtualBox?

**Comment by robertofocke** [comment]
![image](https://user-images.githubusercontent.com/13512662/80312053-877c6f00-87b9-11ea-8076-4fc104dc2f58.png)

**Comment by robertofocke** [comment]
sory, used sudo. it was my error

**Comment by goscickiw** [comment]
I'm having the exact same issue. I tried installing `libasound2-dev`, then compiling again after `make clean`, and also after getting a completely fresh copy of the repository. I did `sudo make uninstall` every time before installing the new compilation. What else could I try? (I'm compiling from develop)

**Comment by BatchDrake** [comment]
@goscickiw what is the exact error? Audio support disabled or Invalid argument? In case it's the first one, could you run:

```
% pkg-config --cflags --libs alsa
```

And paste the output here?

**Comment by goscickiw** [comment]
The error is this:
![Zrzut ekranu z 2020-05-27 19-48-30](https://user-images.githubusercontent.com/39399945/83054738-2e6f5780-a053-11ea-8879-649e974a7e25.png)
`pkg-config --cflags --libs alsa` gives me only this:
``
-lasound
``

**Comment by BatchDrake** [comment]
@goscickiw there was a bug in `SigDigger.pro`. Pull from SigDigger (`develop`) and repeat the build from `make clean && qmake SigDigger.pro`

**Comment by goscickiw** [comment]
It's fixed now, thanks
