### ISSUE TITLE
Time preview: velocity distribution disables sampling & decision controls

### ISSUE THREAD

**Issue by jeffpc** [BatchDrake/SigDigger#112]
Steps to reproduce:

1. do a time domain capture
2. in the "Measurements" tab, click on "Show velocity distribution"
3. dismiss window, and go to "Sampling and decision" tab
4. note that *all* the controls are disabled, on a program restart seems to make them available

**Comment by BatchDrake** [comment]
Thank you for reporting this! I've been experiencing this for a while but didn't have time to figure out how to reproduce it. I'm looking into this ASAP.

**Comment by BatchDrake** [comment]
Changes in `develop`, give it a try.

**Comment by jeffpc** [comment]
The develop change fixes it. Thanks.
