### ISSUE TITLE
Effective rate throttle override doesn't persist between restarts

### ISSUE THREAD

**Issue by jeffpc** [BatchDrake/SigDigger#118]
Steps to reproduce:

1. start replay
2. enable throttle override
3. set effective rate to non-zero
4. close sigdigger
5. start sigdigger

Note that throttle override is still enabled but the rate is 0 and the the scale is "sps".

(If the throttle is *not* active, restarting sigdigger preserves the override state *and* the rate.)

**Comment by BatchDrake** [comment]
It should be fixed now, changes in `develop`

**Comment by jeffpc** [comment]
Your change fixes the problem.  Thanks.
