### ISSUE TITLE
macos 10.11.6: no activable file systems - error

### ISSUE THREAD

**Issue by differentieel** [BatchDrake/SigDigger#119]
hi - downloaded the DMG binary for macOs today - try to open it for installation but got this error: no activable file systems
screenshot in Dutch
![2020-06-01_SigDigger-error](https://user-images.githubusercontent.com/484138/83392601-aa6ff380-a3f5-11ea-9975-02171c34ca6a.png)
my mac has OS X El Captain - version 10.11.6 - on a macbook pro from medio 2009
hope you are able to fix this

**Comment by BatchDrake** [comment]
It looks like the system I used to build this is way too recent. I'll consider building this in an older Macbook. Thanks for reporting!
