### ISSUE TITLE
Scan spectrum size > sdr bandwidth as option ?

### ISSUE THREAD

**Issue by zanco** [BatchDrake/SigDigger#131]
Hi,
Is it possible to set a spectrum scan for multiples of the SDR Bandwidth ? 

For example. scan 1690 - 1708 MHz as 3 X 6 MHz and show them as one scan ?

**Comment by BatchDrake** [comment]
Yep, using the Panoramic Spectrum View. Just press Ctrl+P to open the panoramic spectrum view, set the SDR device and frequency range, and press Start scan.
