### ISSUE TITLE
Feature: enhance bookmarks

### ISSUE THREAD

**Issue by jedi7** [BatchDrake/SigDigger#139]
Hi,
it will be nice if the bookmark will store also modulation, bandwidth and possible also other settings. So fast switch to different signal will be possible.

I can try to implement it, when will be time.

**Comment by BatchDrake** [comment]
If you manage to code this I can include it in SigDigger 0.2. On the other hand, how do we make this information effective? We just set demod bandwidth and configure the appropriate inspector on the GUI? Or do we actually open the inspector? Maybe one click to set the parameters in the GUI, double click to actually open it?

**Comment by jedi7** [comment]
Hi, regarding this I opened this PR: https://github.com/BatchDrake/SuWidgets/pull/13
and https://github.com/BatchDrake/SigDigger/pull/148

**Comment by jedi7** [comment]
Changes merged to develop, so closing. Thanks :)
