### ISSUE TITLE
Unwanted HistogramDialog shows on click after start

### ISSUE THREAD

**Issue by jedi7** [BatchDrake/SigDigger#149]
Steps to reproduce:

1) start SigDigger
2) click on the waterfall
3) the dialog windows HistogramDialog and Sampling windows shows

Showing of HistogramDialog is triggered by HistogramDialog::blanked ->  TimeWindow::onTriggerHistogram -> show histogram

this code is suspicious (HistogramDialog.cpp: 76):
```
  connect(
        this->ui->histogram,
        SIGNAL(blanked()),
        this,
        SIGNAL(blanked()));
```

Any hints how to debug it more?

**Comment by BatchDrake** [comment]
I changed the slot to the blanked signal, to prevent opening a new Windows if it is currently closed, changes in develop. Give it a try.

**Comment by jedi7** [comment]
yeah that's worked HistogramDialog is gone. 
But Sampling window remains still showing. Maybe the same change will help?

**Comment by BatchDrake** [comment]
Done, give it a try

**Comment by jedi7** [comment]
great , working :) thanks
