### ISSUE TITLE
Peak Detection button causes segfault

### ISSUE THREAD

**Issue by kevincroissant** [BatchDrake/SigDigger#15]
Hello,

Using an AirSpy R2 on Debian Buster, with the 0.0.6 AppImage, click the Peak Detection button causes an immediate segfault:
```
/home/kevin/Downloads [kevin@carbon] [11:30]
> ./SigDigger-0.0.6-x86_64.AppImage
[INFO] Using format CF32.
/tmp/.mount_SigDigDAkvFX/AppRun: line 4: 15641 Segmentation fault      $APPDIR/usr/bin/SigDigger.bin
```
Not sure if this is supposed to work yet - if so, let me know how I can help test or what other info you would like.

Thanks!

**Comment by kevincroissant** [comment]
I forgot to mention, the Peak Hold button causes the exact same behavior.

**Comment by BatchDrake** [comment]
I've been trying to reproduce this behavior -both from sources and AppImage- but no luck so far. Could you attach the XML files saved in ```~/.suscan/config``` to this issue?

Thanks!

**Comment by kevincroissant** [comment]
Here you go:
[config.zip](https://github.com/BatchDrake/SigDigger/files/3538302/config.zip)
