### ISSUE TITLE
Hash collision!!! Fatal error!!

### ISSUE THREAD

**Issue by phirippu** [BatchDrake/SigDigger#159]
Hi!

On Ubuntu Hirsute the application does not start with the "Hash collision!!! Fatal error!!" line. 

Qt 5.15.2
Ubuntu 21.04 [linux version 5.11.0-33-lowlatency]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 RTM HLE

**Comment by phirippu** [comment]
Using suscan version 0.2.0 (custom build on Aug 24 2021 at 16:05:24 (10.3.0))
Using sigutils version 0.2.0 (custom build on Aug 24 2021 at 16:04:19 (10.3.0))

**Comment by BatchDrake** [comment]
Hi @phirippu 

Sorry for the late answer, I am still going through all open issues today. Things changed a lot since 0.2.0, is SigDigger still failing?

Cheers,

**Comment by phirippu** [comment]
No, not anymore =)

**Comment by BatchDrake** [comment]
Cool! I am therefore closing the issue, thanks for reporting!
