### ISSUE TITLE
Interesting software but compiling it is tedious

### ISSUE THREAD

**Issue by kord1e** [BatchDrake/SigDigger#187]
I noticed the following issues when compiling Sigdigger on Linux (Debian):

1) There are 4 software in total to compile and install. It would be much easier if the libraries were included in the main sigdigger tree. (Keeping them separate makes it easier to maintain them independently, I guess, but perhaps syncing them into Sigdigger project could be automated?)

2) SuWidgets is installed into /usr/lib/... by default, this is against the common convention of installing self compiled software into /usr/local/{bin,lib...}/... Sigutils, suscan and sigdigger itself seem to be installed mostly into /usr/local/... 

3) Even if you configure SuWidgets and Sigdigger to install into /usr/local/... , SigDigger still seems to assume that the libraries should be loaded from /usr/lib/... ?? And if they are not there, it doesn't start and complains about missing libraries.

**Comment by BatchDrake** [comment]
Hi, and thanks for your feedback.

1. This is something that has been pointed out earlier by other people. However, have in mind that SigDigger is not the only project depending on Sigutils, Suscan still needs to be able to run in headless systems with no GUI and I have other projects depending on SuWidgets (like QStones). I wrote scripts that attempt to speed this up (like https://actinid.org/blsd, see the user manual in doc/ for details). I considered turning SigDigger into a recursive repositorio (i.e. referencing SuWidgets and so on) but never had the time to do it right.
2. Actually, it is installed in your Qt installation path. The rationale was to make sure that you don't mix SuWidgets linked against one Qt version with a SigDigger linked against a different one.
3. That is... odd. The continuous integration system I have setup here in GitHub does not install anything system-wide, neither with blsd nor for the AppImages. And many users rely on the ability of building SigDigger without installing anything system-wide. Can you describe exactly how you are attempting to do this?
