### ISSUE TITLE
configure  succeeds and then the build fails with the missing WFHelpers.h header

### ISSUE THREAD

**Issue by yurivict** [BatchDrake/SigDigger#195]
```
include/Suscan/Library.h:37:10: fatal error: 'WFHelpers.h' file not found
#include <WFHelpers.h>
         ^~~~~~~~~~~~~
```

**Comment by BatchDrake** [comment]
Hi Yuri,

Is this error still occurring? How are you compiling SigDigger exactly? Can
you detail the steps you followed?

Cheers,

**Comment by yurivict** [comment]
I use qmake.

**Comment by BatchDrake** [comment]
Hi,

Still, this should work out of the box. Which version in particular? Is
this Qt5 or Qt6?

You are building this on FreeBSD right? Which version in particular?

Cheers,

**Comment by yurivict** [comment]
It's Qt5.

The original error occurred when suwidgets was missing.
Once suwidgets is installed ```-I${LOCALBASE}/include/SuWidgets``` had to be added in order for SigDigger to find the WFHelpers.h header.

**Comment by yurivict** [comment]
It's FreeBSD 13.1 STABLE

**Comment by chron0** [comment]
I have the same issue with gentoo and 0.3.0:

```
_WARNINGS -DSIGDIGGER_HAVE_ALSA -D_SU_SINGLE_PRECISION -DHAVE_VOLK=1 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Iinclude -I/usr/include/qt5/SuWidgets -I/usr/include/suscan -I/usr/include/suscan/util -I/usr/include/sigutils -I/usr/include/sigutils/util -I/usr/include/opus -I/usr/include/libxml2 -I/usr/include/qt5 -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I. -I/usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o AppUI.o App/AppUI.cpp
In file included from App/Application.cpp:21:
include/Suscan/Library.h:35:10: fatal error: analyzer/discovery.h: No such file or directory
   35 | #include <analyzer/discovery.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2832: Application.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from include/AppConfig.h:29,
                 from App/AppConfig.cpp:20:
include/Version.h:23:10: fatal error: sigutils/version.h: No such file or directory
   23 | #include <sigutils/version.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2795: AppConfig.o] Error 1
In file included from App/AppUI.cpp:22:
include/MainSpectrum.h:26:10: fatal error: WFHelpers.h: No such file or directory
   26 | #include <WFHelpers.h>
      |          ^~~~~~~~~~~~~
```

0.1.0 built without a problem - but neither suwidgets nor suscan deployed a WFHelpers.h during install and there is none /usr/*

**Comment by BatchDrake** [comment]
Make sure that you are building the latest WFHelpers.h from develop. The
same applies to Sigutils and Suscan.

**Comment by chron0** [comment]
yeah, i think thats the issue, i was hunting down the headers and it seems the are only in master but not in 0.1 release on suscan and suwidgets

**Comment by chron0** [comment]
this was my conclusion after looking thru master branch and finding a lot of files that simply werent in my system and also in the 0.1.0 release package. I have created local ebuilds in my overlay and bumped sigutils, suscan and suwidgets to -9999 (git master) and they compiled without a problem. consequently my sigdigger-0.3.0 now also compiled perfectly. 

I think it would make sense to bump sigutils, suscan and suwidgets to a 0.3.0 release where they match so that package and build maintainers for the distros can pick it up and avoid this dep confusion.

**Comment by BatchDrake** [comment]
Yeah, you are absolutely right. I got into this bad habit of only caring about SigDigger versioning, but this is something I should do in all projects at the same time.

**Comment by chron0** [comment]
and ofc, big thank you for putting in all the work and sharing it!
