### ISSUE TITLE
SigDigger unstalls headers without libraries

### ISSUE THREAD

**Issue by yurivict** [BatchDrake/SigDigger#196]
For example:
```
include/SigDigger/Suscan/Serializable.h
include/SigDigger/Suscan/Source.h
include/SigDigger/Suscan/SpectrumSource.h
include/SigDigger/TLESourceConfig.h
include/SigDigger/TabWidgetFactory.h
include/SigDigger/ToolWidgetFactory.h
```

This is probably done by mistake because how can these headers be useful for an application?

**Comment by BatchDrake** [comment]
Hi Yuri,

This is intended. These headers are part of the public API exposed to
plugins. You need these in order to develop plugins for SigDigger.

Cheers,
