### ISSUE TITLE
DC Spike in middle of spectrum display. Request to please fix in software.

### ISSUE THREAD

**Issue by John-Telek** [BatchDrake/SigDigger#200]
I get this spike in the middle of my display on the center frequency. The remove DC button does not do anything.
![IMG_0936](https://user-images.githubusercontent.com/126052698/220574852-1fa9c534-ad7b-4fb2-94fd-2553d43efb7e.jpg)

Any suggestions please ?

Cheers,
   John Telek

**Comment by John-Telek** [comment]
This other spike is also present to the left of center. I'm getting this with no antenna. Any ideas ?

![Screenshot from 2023-03-01 20-11-17](https://user-images.githubusercontent.com/126052698/222095287-88c3013f-9b86-4a17-a30d-11bd1173aa0b.png)

**Comment by BatchDrake** [comment]
Does that spike move when you change the frequency?

**Comment by John-Telek** [comment]
No it stays in the center. It's to do with the DC component. The DC remove button does nothing. I have no idea where the one on the left is from, and adjusting audio cutoff frequency can produce weird audio products.
Cheers,
      JT

**Comment by BatchDrake** [comment]
Yeah, I would not expect the one in the center to move, I was curious about the one in the left. That can perfectly be an artifact of the RTL-SDR, caused by harmonics (if it moves with the spectrum) or images of something else (if it moves against the spectrum).

**Comment by John-Telek** [comment]
Mate, would it be ok to post a video of my issues ?

Cheers,
   John

**Comment by BatchDrake** [comment]
Sure, go ahead!

**Comment by John-Telek** [comment]
I just tried the latest build and the DC spike is still there.

John.   :)

**Comment by BatchDrake** [comment]
Fixed, launching a development build now.

**Comment by John-Telek** [comment]
No worries mate. Thanks,

JT

**Comment by BatchDrake** [comment]
https://github.com/BatchDrake/SigDigger/releases/tag/latest

**Comment by John-Telek** [comment]
Still there.

JT

**Comment by BatchDrake** [comment]
Press Ctrl+L and post a screenshot of the log window

**Comment by BatchDrake** [comment]
I've just fixed something (DC correction worked for file sources only, not for devices without DC correction support), launching a new build now.

**Comment by BatchDrake** [comment]
Download this again: https://github.com/BatchDrake/SigDigger/releases/tag/latest if this is not fixing it, this means that the SDR receiver supports DC offset correction but it is not working properly (on the device's side)

**Comment by John-Telek** [comment]
Here is the Log window. Doesnt say anything.

JT

**Comment by John-Telek** [comment]
Will doe mate. Thak you.  :)

JT

**Comment by John-Telek** [comment]
The DC remove works on ather apps so my SDR dongle should be ok.

JT

**Comment by John-Telek** [comment]
YAAYYY It works. :) :) :)

Thank you. How did you fix it pls ?

Cheers,
   JT.

**Comment by BatchDrake** [comment]
I basically did it on software. I compute a sample average on every read and use it to update the DC offset, which is subtracted from the samples. 

I am still worried about the performance impact though, I will see whether it makes sense to use Volk to speed up things here.
