### ISSUE TITLE
Keyboard issues in Doppler tool

### ISSUE THREAD

**Issue by eb3frn** [BatchDrake/SigDigger#208]
Check the input text boxes where in someone's like the Rate bias is impossible to write a new value. The Freq rate is OK.

Thanks!

**Comment by BatchDrake** [comment]
Cannot reproduce. I can write new values just fine:

![Uploading Captura de pantalla de 2023-05-11 19-19-13.png…]()

**Comment by BatchDrake** [comment]
Cannot reproduce. I can write new values just fine:

![Captura de pantalla de 2023-05-11 19-19-13](https://github.com/BatchDrake/SigDigger/assets/610895/738237e6-ebca-4c65-b9f8-e5a3bac5a9ca)
