### ISSUE TITLE
Device title/name is not shown in main window

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#50]
When a new device (SDR) is started, the name or label is not shown in the window title. It only shows `Unlabeled source`
Look at the screenshot

<img width="1792" alt="Screenshot 2020-01-26 at 21 53 43" src="https://user-images.githubusercontent.com/12119776/73142528-0d402f80-4090-11ea-9e21-de837d738c63.png">

**Comment by BatchDrake** [comment]
Yep, that's because the source itself does not have a title. If you save it with a name it should show it. Maybe it's not too clear, now that I think of it. I'm marking this as UX issue.
