### ISSUE TITLE
Scan button in Panoramic spectrum view

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#51]
This is a suggestion: maybe it's better to either have a "stop" button, or change the name of the "scan" button when it's presses, so it's easier for the user to understand (also more accessible from a UX standpoint). Or maybe implement it like a button that has on/off switch

**Comment by BatchDrake** [comment]
Good idea!

**Comment by BatchDrake** [comment]
Done. Changes in develop.
