### ISSUE TITLE
 Mysterious build issue on macOS (lacking library name)

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#53]
I open this issue as a reference for future, as this happened in all the repos including SigDigger.
I think it's because of volk.
Removing the empty `-l` from Makefile resolves the issue.
The linker error log is something like this:
```
ld: library not found for -l-lfftw3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SigDigger.app/Contents/MacOS/SigDigger] Error 1
```

**Comment by BatchDrake** [comment]
This has been fixed, right?

**Comment by mehdideveloper** [comment]
Yes
