### ISSUE TITLE
Settings dialog resize

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#61]
Do you need to allow the user to resize the settings dialog? It's not a big deal, but usually these dialogs are fixed size, as there's no need to change the size. I'm not sure if it was like this from the first day, or you changed it because of #57

**Comment by BatchDrake** [comment]
Well, it shouldn't and if it is the case, it is certainly a UI bug.

**Comment by mehdideveloper** [comment]
Look at the two screenshots (original, and resized)
<img width="1667" alt="Screenshot 2020-02-11 at 18 39 55" src="https://user-images.githubusercontent.com/12119776/74262844-f3dceb80-4cfd-11ea-9508-0ae188119ca8.png">
<img width="712" alt="Screenshot 2020-02-11 at 18 39 45" src="https://user-images.githubusercontent.com/12119776/74262847-f50e1880-4cfd-11ea-846d-f2b75580b092.png">

**Comment by BatchDrake** [comment]
It should have been fixed now in feature/ux-improvements

**Comment by mehdideveloper** [comment]
It is fixed 👍
