### ISSUE TITLE
Source settings inconsistency

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#62]
When I choose a device in the initial Source dialog, the `Remove DC` box is checked by default.
And then I start the device, but now the `DC remove` box in the Source pane in the right, is not selected!
Is this a bug or intentional?
Also as you notice, the two boxes are using different letter cases for the same word combination (and in a different order)

**Comment by BatchDrake** [comment]
It should have been fixed now in feature/ux-improvements

**Comment by mehdideveloper** [comment]
It's fixed 👍
