### ISSUE TITLE
getSamplesPerPixel is missing

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#63]
Compiling SigDigger from feature/ux-improvements fails because:
`Components/TimeWindow.cpp:687:45: error: no member named 'getSamplesPerPixel' in 'Waveform'`

**Comment by BatchDrake** [comment]
Changes stilk at home, I will push changes later today. In the meantime,
write a function in Waveform.h that returns the qreal this->sampPerPx.

**Comment by mehdideveloper** [comment]
This fixes the issue 👍
