### ISSUE TITLE
Check the minimum and maximum frequency

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#70]
I have a suggestion:
check the upper and lower supported frequencies for the connected device and don't allow the user to tune to anything outside the range (neither show them in the spectrum)
I think this is feasible using SoapySDR's API.
I tried to test the latest commits, and the frequency was 0 (on the settings pane). I'm not sure if it was always like this, or it's new. Anyway, I clicked on the start and then the spectrum was showing the centre frequency of 0 and negative frequencies to the left ! (The connected device was AirSpy one which does not support below 24MHZ)

**Comment by BatchDrake** [comment]
That's indeed a bug. The frequency is not being refreshed in the settings dialog. Also, the arrow symbols don't show in all machines. I will have to use symbolic icons here.

**Comment by mehdideveloper** [comment]
This would be my top request (as a regular user)  to be fixed.
It's annoying to set the frequency everytime I fire up the app to do some tests

**Comment by BatchDrake** [comment]
I am failing to reproduce this at home, still looking into it.

**Comment by mehdideveloper** [comment]
Screenshot for reference:

<img width="1680" alt="Screenshot 2020-02-25 at 13 55 02" src="https://user-images.githubusercontent.com/12119776/75249400-8be6d480-57d6-11ea-9708-fca6bf65d2f6.png">

**Comment by BatchDrake** [comment]
I think I fixed it. Pull the latest changes from ux-improvements as usual.

**Comment by mehdideveloper** [comment]
Yes it is fixed 👍
