### ISSUE TITLE
Two options for full screen on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#71]
Hey
On macOS there are 2 options in the View menu to go full screen. Look at the attached screenshot:

<img width="244" alt="Screenshot 2020-02-21 at 11 50 48" src="https://user-images.githubusercontent.com/12119776/75028763-25457c00-54a1-11ea-84b6-d7c852762482.png">

**Comment by BatchDrake** [comment]
Dang. I'd like to keep the F11 behavior as it would work in a platform-independent way. Some people found a solution using Objective C, but maybe is too cumbersome: https://forum.qt.io/topic/60623/qt-5-4-2-os-x-10-11-el-capitan-how-to-remove-the-enter-full-screen-menu-item/6

**Comment by BatchDrake** [comment]
Just took the path of least resistance and removed the full screen option completely in MacOS X. Changes in the usual branches.

**Comment by mehdideveloper** [comment]
Fixed 👍
