### ISSUE TITLE
Adjusting the visual gain

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#72]
When working on weak signals, we need to have an option to either increase the visual gain or expand the spectrum to -100dB (instead of -50)
For example look at the attached screenshot: I am trying to receive some weak signals with AirSpy HF+ and even with the maximum gain settings, signals can't be properly shown.
 
<img width="1792" alt="Screenshot 2020-02-22 at 20 07 47" src="https://user-images.githubusercontent.com/12119776/75097830-688e1080-55af-11ea-9263-9bc56a2c87e6.png">

**Comment by BatchDrake** [comment]
You already can. Use the mouse wheel on the left side of the spectrum.
There should also be a control in the FFT panel calles "panadapter range".

**Comment by mehdideveloper** [comment]
Oh! I never used it 🙈 
Thanks
