### ISSUE TITLE
Filter settings

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#73]
Is there a way to adjust filter bandwidth in SigDigger?
Look at the attached screenshot. The WFM signal had a bigger bandwidth of what's highlighted in the spectrum. It should be very nice if user can change the filter bandwidth. Or maybe some default pre-sets would be good as well. Like 2.7KHZ for SSB, something between 6-9KHZ for AM and 200KHZ(?!) for FM. 
Which also brings me to the 2nd question: have you considered having two separate NFM and WFM  demodulators?

**Comment by mehdideveloper** [comment]
<img width="1792" alt="Screenshot 2020-02-23 at 20 07 17" src="https://user-images.githubusercontent.com/12119776/75118907-adcd4380-567e-11ea-8716-401166953535.png">

**Comment by mehdideveloper** [comment]
This is crazy! I have been using this app for a while and hadn't noticed that you can change the width with mouse !!

**Comment by BatchDrake** [comment]
Dude 😂😂😂

**Comment by BatchDrake** [comment]
I definitely have to prepare a small manual with the next release.

**Comment by mehdideveloper** [comment]
I will help you with the manual

**Comment by BatchDrake** [comment]
I've just opened an issue for that: https://github.com/BatchDrake/SigDigger/issues/74
