### ISSUE TITLE
Slow waterfall

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#77]
After pulling the recent changes from feature/ux-improvements, the waterfall has slowed down (all the other settings are the same as before)

**Comment by BatchDrake** [comment]
Added changes to suscan in performance-improvements. Now it should work, even if the device is delivering sample buffers very slow.

**Comment by mehdideveloper** [comment]
This is better now (though I have to test more)

**Comment by mehdideveloper** [comment]
This is also fixed
