### ISSUE TITLE
Record button label

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#78]
I think it would be better if the label of the record button is changed to something like "stop" when the recording is started (or maybe 2 separate start/stop buttons are used?!)

**Comment by BatchDrake** [comment]
You mean the audio recorder, right? I'll give it a look.

**Comment by BatchDrake** [comment]
Done. Give it a look.

**Comment by mehdideveloper** [comment]
Thanks. Much better now (IMHO)
