### ISSUE TITLE
Audio sample rates list

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#80]
I have a suggestion for the "Sample rate" drop-down box in the "Audio preview" pane. Right now it seems to show a fixed set of rates. I think it would be good if it shows the actual sample rates supported by the default output device. For example it has 196,000, but none of my audio devices support anything larger than 192,000

**Comment by BatchDrake** [comment]
That is a typo. The output rate should be 192000. I'm fixing that.

Also, the audio feature needs a redesign so it can be configured in the config dialog.
