### ISSUE TITLE
Wrong sample rates in the settings dialog

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#87]
When selecting an input device from the Source tab of the settings dialog, I assume SigDigger gets the available supported sample rates from Soapy.
This does not work always!
For example my laptop's microphone has 4 sample rates according to SoapySDR: 44.1, 48, 88.2 and 96 Ksps.  This is shown correctly in the "Sample rate" drop down.
But when I select my headphone (which has a built-in microphone) and according to SoapySDR supports ` 0.0441, 0.048, 0.0882, 0.096, 0.1764, 0.192 MSps`, SigDigger only shows 16ksps for it !

**Comment by BatchDrake** [comment]
Caused by weird behavior of the old SoapySDR's sample rate query API. Leaving for SigDigger 0.2
