### ISSUE TITLE
Bug in the "About" dialog

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#88]
Clicking on any links (email, website, twitter handle) on the About dialog makes the textbox empty and it's not fixed/reverted, unless the app is restarted.

Also a minor thing: About dialog has two Ok/Cancel buttons but both do the same task

**Comment by BatchDrake** [comment]
I think I have fixed it. Pull from develop and try again.

**Comment by mehdideveloper** [comment]
This is only solved in the `Authors` tab. `License - original code` still has the issue

**Comment by BatchDrake** [comment]
You are right, try again.

**Comment by mehdideveloper** [comment]
fixed 👍
