### ISSUE TITLE
Bug in device renaming

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#89]
I'm not sure if this is intentional, but seems like a bug:
I can go to "Capture devices" window (Ctrl+D) and rename the device ID or driver, but it has no effect. If I close the window and open again, it reverts to the default name

**Comment by BatchDrake** [comment]
That's a bug. Device renaming is not a feature.

**Comment by BatchDrake** [comment]
Fixed. You should not be able to edit the entries now.
