### ISSUE TITLE
error in make in SigDigger 

### ISSUE THREAD

**Issue by fe8769a** [BatchDrake/SigDigger#90]
Hello

Doing a make while compiling Sigdigger , I have the following error :./ui_Config.h: In member function ‘void Ui_Config::retranslateUi(QDialog*)’:
./ui_Config.h:822:23: error: ‘class QComboBox’ has no member named ‘setCurrentText’; did you mean ‘setCurrentIndex’?
         profileCombo->setCurrentText(QString());
                       ^~~~~~~~~~~~~~
                       setCurrentIndex
Makefile:648: recipe for target 'AppConfig.o' failed
make: *** [AppConfig.o] Error 1
I didn't find any explaination 

OS is Xubuntu 18.04.4 

Thanks for help

**Comment by BatchDrake** [comment]
Hi, thank you for your feedback. What Qt version are you using?

**Comment by fe8769a** [comment]
Please close this call . I did a new reinstall
