### ISSUE TITLE
compile error in macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#91]
There's a new mismatch between two operands in the recent changes in develop:
`CarrierDetector.cpp` line 133:
`acc += psd * SU_C_EXP(I * M_PI * nFreq);`
`I` is std::complex. Changing it to something like 
`acc += psd * SU_C_EXP(SU_C_REAL(I) * M_PI * nFreq);`
fixes

**Comment by BatchDrake** [comment]
The problem is that that change, mathematically, does not make sense. SU_C_EXP must accept the imaginary unit times pi times `nFreq`.

**Comment by BatchDrake** [comment]
Also, I need the specific error.

**Comment by mehdideveloper** [comment]
Sorry for the late reply. I think you solved this, right? I don't get errors anymore (pulled the latest changes)

**Comment by BatchDrake** [comment]
Yep, days ago. Anyways, get ready because there's a big feature in the oven and a lot of things may break in the following days.
