### ISSUE TITLE
Can't find Decider.h on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SigDigger#94]
Hi
I pulled the recent changes from develop.
All the repos compiled successfully except SigDigger which complains about the Decider.h not found, although I can find it installed under `/usr/local/Cellar/qt/5.14.1/include/SuWidgets`

**Comment by BatchDrake** [comment]
It should be fixed now.

**Comment by mehdideveloper** [comment]
Fixed 👍
